os: osx
language: python
#python:
#  - "3.6"
#  - "3.7"
matrix:
 include:
   - name: "Python 3.7.4 on macOS"
        os: osx
        osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
        language: shell       # 'language: python' is an error on Travis CI macOS
addons:
  homebrew:
    update: true
    packages:
      - geos
      - gdal
      - proj
services:
  - docker
install:
  - pip install -r requirements.txt
before_script:
  - docker-compose up
  - cd backend
script:
  - python manage.py test