#addons:
#  apt:
#    sources:
#      - sourceline: 'ppa:ubuntugis/ppa'
#    packages:
#    - binutils
#    - libproj-dev
#    - gdal-bin
#    - libgdal-dev
services:
  - docker
#install:
#  - pip install -r requirements.txt
before_script:
  - sudo service postgresql stop
  - docker-compose up --build -d
#  - cd backend
script:
  - docker-compose exec webapp ./test.sh