#os: osx
language: python
python:
  - "3.6"
  - "3.7"
addons:
  homebrew:
    packages:
    - geos
services:
  - docker
install:
  - pip install -r requirements.txt
before_script:
  - docker-compose up
  - cd backend
script:
  - python manage.py test