#os: osx
language: python
python:
  - "3.6"
  - "3.7"
services:
  - docker
install:
  - pip install -r requirements.txt
before_script:
  - docker-compose up
  - cd backend
script:
  - backend/manage.py test