#os: osx
language: python
python:
  - "3.6"
  - "3.7"
addons:
  apt:
    packages:
#    - geos
#    - gdal
#    - proj
    - binutils
    - libproj-dev
    - gdal-bin
services:
  - docker
install:
  - pip install -r requirements.txt
before_script:
  - sudo service postgresql stop
  - docker-compose up --build
  - cd backend
script:
  - python manage.py test