version: "3.7"
services:
#  webapp:
#    container_name: "spatial_web-app"
#    build: .
#    working_dir: /code/backend
#    command: python3 manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
  database:
    container_name: "spatial_postgres"
    image: kartoza/postgis:9.6-2.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user001
      - POSTGRES_PASS=123456789
      - POSTGRES_DBNAME=gis