version: "3.7"
services:
#  webapp:
#    container_name: "spatial_web-app"
#    build: .
#    working_dir: /code/backend
#    command: ["./run_development_server.sh"]
#    volumes:
#      - .:/code
#    ports:
#      - 8000:8000
#    depends_on:
#      - database
  database:
    container_name: "spatial_db"
    image: kartoza/postgis:9.6-2.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user001
      - POSTGRES_PASS=123456789
      - POSTGRES_DBNAME=gis