# Generated by Django 2.2.4 on 2019-08-17 19:14

import json
import os

from django.db import migrations


def load_initial_data(apps, schema_editor):
    PointOfSale = apps.get_model('points_of_sale', 'PointOfSale')

    initial_data_directory = os.path.join(os.path.dirname(__file__), 'data')
    initial_data_filename = 'initial_data.json'
    with open(os.path.join(initial_data_directory, initial_data_filename)) as file_data:
        data = json.load(file_data)
        print(data['pdvs'][0])
        for pos_data in data['pdvs']:
            new_pos_data = {
                'id': pos_data['id'],
                'trading_name': pos_data['tradingName'],
                'owner_name': pos_data['ownerName']
            }
            point_of_sale, _ = PointOfSale.objects.get_or_create(**new_pos_data)
            point_of_sale.save()

    # raise Exception()


class Migration(migrations.Migration):
    dependencies = [
        ('points_of_sale', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]
